# Generated by Django 5.1.2 on 2024-12-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='plantio',
            name='dicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantio',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendario.cidade'),
        ),
        migrations.AlterUniqueTogether(
            name='plantio',
            unique_together={('cidade', 'cultura', 'bandeja', 'especie', 'celula', 'variedade')},
        ),
        migrations.RemoveField(
            model_name='plantio',
            name='produtividade',
        ),
    ]
