# Generated by Django 5.1.2 on 2024-12-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_alter_bandeja_nome_alter_cidade_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantio',
            name='celula',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='especie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantio',
            name='variedade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
