# Generated by Django 5.1.2 on 2024-12-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_alter_plantio_celula_alter_plantio_especie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='quantidade_mudas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
