# Generated by Django 5.1.2 on 2024-12-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0005_remove_evento_descricao_evento_quantidade_mudas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='data_notificacao',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='enviada',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='mensagem',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='plantio',
        ),
        migrations.AddField(
            model_name='notificacao',
            name='imgUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='titulo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
